spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopic: "order-topic"
    kafkaMessageTopic2: "order-status-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
    kafkaMessageGroupId2: "kafka-message-group-id2"